CC		= g++ 
CFLAGS		= -g -c -Wall -std=c++14
LDFLAGS		= 
SOURCES		= client.cpp TCPConnector.cpp TCPStream.cpp Parser.cpp
INCLUDES	= -I.
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= client

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $^ -o $@

clean:
	rm -rf $(OBJECTS) $(TARGET)